#!/usr/bin/env python3
"""
Auto-categorize all unmapped rexresearch.com folders by analyzing
folder names + file titles + filenames with keyword matching.
Also re-categorizes files that have content_preview text.
Outputs updated index.json with expanded categories and meta-categories.
"""

import json
import re
import os

INPUT_FILE = os.path.join(os.path.dirname(__file__), 'index.json')
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), 'index.json')

# ─── Category keywords (same as PowerShell script, expanded) ───
CATEGORY_KEYWORDS = {
    "Aether Physics": ["aether", "ether", "zero point", "zpe", "vacuum energy", "casimir",
        "quantum vacuum", "scalar wave", "longitudinal", "radiant energy", "cold electricity",
        "subtle energy", "tachyon", "torsion field", "aetheric", "etheric", "prana", "orgone",
        "odic", "vril", "morphic", "morphogenetic", "biophotonic", "biophoton", "formative force",
        "life force", "vital force", "electrogravitic", "monatomic", "ormus", "orme",
        "overunity", "over-unity", "fuelless", "free energy", "zero-point", "scalar",
        "longitudinal wave", "energy density", "quantum field", "implosion", "schauberger",
        "vortex energy", "torsion", "aether ", "ether ", "radiant", "cold electric",
        "tap energy", "extract energy", "vacuum", "zero point energy", "zpe",
        "meyl", "konstantin meyl", "scalar potential", "whittaker", "neutrino",
        "energy sea", "stochastic electrodynamics", "sed", "plasmoid", "evu", "evo",
        "charge cluster", "exotic vacuum object", "shoulders", "ken shoulders",
        "pulsed plasma", "plasma glow", "glow discharge", "plasmoid"],
    "Energy Generation": ["free energy", "overunity", "perpetual", "self-running",
        "energy extraction", "generator", "alternator", "power generation", "fuelless",
        "magnetic motor", "rossi", "e-cat", "cold fusion", "lenr", "fusion reactor",
        "thermoelectric", "tesla coil", "energy machine", "moray", "hendershot",
        "testatika", "searl", "quantum energy", "power device", "energy device",
        "newman", "bedini", "lutec", "perendev", "motor", "engine", "power",
        "over unity", "over-unity", "self running", "fuel less", "free-energy",
        "magnetic motor", "rossi", "e-cat", "cold fusion", "lenr", "low energy nuclear",
        "fusion", "thermoelectric", "tesla coil", "energy machine", "moray",
        "hendershot", "testatika", "searl", "quantum energy", "power device",
        "energy device", "newman", "bedini", "lutec", "perendev", "coler",
        "meyer", "stanley meyer", "water fuel", "hho", "brown gas", "brown's gas",
        "electrolysis", "fuel cell", "hydrogen", "overunity", "over unity",
        "papp", "papp engine", "noble gas", "sirls", "chukanov", "ball lightning",
        "plasmoid", "charge cluster", "evo", "exotic vacuum object",
        "swartz", "moxy", "moxie", "nano", "coalesced", "superwave", "sonoluminescence",
        "cavitation", "sonofusion", "bubble fusion", "acoustic cavitation",
        "griggs", "hydrosonic", "hydrodyn", "pump", "kinetic", "thermodynamic",
        "entropy", "negentropy", "syntropy", "second law", "thermodynamics",
        "maxwell", "demon", "maxwell demon", "information", "bit", "entropy",
        "pump", "hydraulic", "pneumatic", "compressor", "turbine"],
    "Water": ["water", "structured water", "ez water", "exclusion zone",
        "fourth phase", "hexagonal", "vortex water", "revitalized",
        "nanobubble", "desalination", "graphene filter", "pollack",
        "gel water", "interfacial", "water memory", "water crystal",
        "living water", "sacred water", "ormus water", "alkaline water",
        "ionized", "hydration", "aqua", "water treatment", "water purification",
        "electrolysis", "schauberger", "dew", "fog", "dew pond", "dew harvest",
        "air well", "dew harvest", "fog fence", "fog collection", "condensation",
        "condense", "water from air", "atmospheric water", "water generator",
        "grander", "revitalized water", "water structuring", "water vortex",
        "cylinder", "vortex", "implosion", "water implosion"],
    "Magnetism": ["magnet", "magnetic", "paramagnetism", "diamagnetism",
        "ferromagnetism", "electromagnet", "neodymium", "lodestone",
        "magnetic field", "magnetic resonance", "magnet motor", "magnetism",
        "biomagnetism", "magnet therapy", "halbach", "magnetic levitation",
        "eddy current", "permeability", "gauss", "magnetohydrodynamic",
        "davis", "rawls", "magnet", "ferromag", "ferro", "maglev",
        "magnetic", "em clutch", "electromagnetic clutch", "rabinow"],
    "Gravity": ["gravity", "antigravity", "anti-gravity", "gravitation",
        "weight reduction", "gravitational", "g-field", "inertia",
        "spacetime", "warp drive", "gravitomagnetic", "graviton",
        "acceleration", "centrifugal", "centripetal", "levitation",
        "buoyancy", "podkletnov", "tajmar", "anti grav", "anti-grav",
        "gyro", "gyroscope", "gyroscopic", "precession", "nutation",
        "reactionless", "propellantless", "space drive", "space drive",
        "mills", "mills space drive", "inertial", "inertia drive",
        "thrust", "thuster", "em drive", "cannae", "shawyer",
        "godin", "roschin", "lifter", "ionocraft", "biefeld", "brown",
        "electrogravitic", "electrogravitics", "field effect",
        "gravitic", "gravity control", "weight loss", "mass reduction"],
    "Light": ["light", "photon", "optics", "spectrum", "color therapy",
        "colour", "luminescence", "fluorescence", "phosphorescence",
        "infrared", "ultraviolet", "laser", "coherent light", "biophoton",
        "spectroscopy", "refraction", "diffraction", "polarization",
        "prism", "spectrochrome", "dinsah", "chromotherapy", "phototherapy",
        "photonics", "fiber optic", "dinshah", "color", "colour",
        "light therapy", "light emitting", "led", "oled",
        "hologram", "holography", "holophonic", "holophonics",
        "zuccarelli", "kilner", "aura", "human energy field",
        "aura photography", "kirlian", "electrophotography",
        "gdv", "gas discharge visualization"],
    "Electric Universe": ["plasma", "electric universe", "birkeland",
        "aurora", "solar wind", "corona", "discharge", "ionosphere",
        "magnetosphere", "electric sun", "plasma cosmology", "peratt",
        "alfven", "z-pinch", "plasma focus", "plasma discharge",
        "filament", "nebula", "cosmology", "big bang", "cosmic",
        "galaxy", "thornhill", "talbott", "scott", "safire",
        "electric sun", "solar", "stellar", "star", "sun",
        "plasma", "arc", "spark", "glow", "discharge tube",
        "plasma gun", "plasma jet", "plasma torch", "plasma channel",
        "lightning", "ball lightning", "st elmo", "fire", "plasma ball"],
    "Psychotronics": ["radionics", "radiesthesia", "dowsing", "pendulum",
        "shape power", "psychotronics", "psionics", "radionic",
        "stick pad", "rub plate", "witness", "reagent",
        "se-5", "se5", "de la warr", "malcolm rae", "drown",
        "turenne", "isotron", "koom", "lucas", "every advantage",
        "biolocation", "bioloc", "dows", "geopathic", "ley line",
        "earth energy", "geomancy", "feng shui", "biogeometry",
        "shape", "form", "resonator", "broadcast", "frequency",
        "rate", "subtle energy", "intent", "thought form",
        "sigil", "symbol", "geometric", "sacred"],
    "Consciousness": ["consciousness", "awareness", "perception",
        "cognition", "psi", "esp", "remote viewing", "telepathy",
        "intuition", "sentience", "meditation", "brainwave",
        "binaural", "isochronic", "entrainment", "neurofeedback",
        "biofeedback", "heartmath", "coherence", "psychedelic",
        "entheogen", "ayahuasca", "plant medicine", "radin",
        "mishlove", "hypnosis", "hypnotic", "trance", "altered state",
        "dream", "lucid", "out of body", "near death", "nde",
        "reincarnation", "past life", "channeling", "medium",
        "psychic", "clairvoyant", "precognition", "premonition",
        "psychokinesis", "pk", "telekinesis", "distant healing",
        "prayer", "intention", "mind", "mental"],
    "Biology": ["biology", "biological", "organism", "cell", "dna",
        "rna", "gene", "genetic", "embryo", "embryology", "metamorphosis",
        "evolution", "morphic field", "epigenetic", "membrane", "protein",
        "enzyme", "bacteria", "virus", "microbiome", "fungi", "mycelium",
        "stem cell", "regeneration", "morphogenesis", "tissue", "organ",
        "transmutation", "kurashov", "sahno", "kervran", "biological transmutation",
        "biotransmutation", "microbial", "microorganism", "protozoa",
        "algae", "spirulina", "phytoplankton", "plankton",
        "biophoton", "bioluminescence", "biofield", "bio electromagnetic",
        "bioelectric", "bioelectric", "galvanotaxis", "electrotaxis",
        "electroculture", "electro culture", "plant growth", "germination",
        "seed", "sprout", "photosynthesis", "chlorophyll",
        "cannabis", "hemp", "medical marijuana", "cannabinoid",
        "thc", "cbd", "terpene", "flavonoid"],
    "Health Medicine": ["health", "medicine", "medical", "healing",
        "therapy", "treatment", "disease", "cancer", "covid",
        "vaccine", "immune", "nutrition", "supplement", "herbal",
        "tincture", "homeopathy", "naturopath", "holistic",
        "alternative medicine", "detox", "antioxidant", "longevity",
        "wellness", "remedy", "clinical", "pharmaceutical",
        "frequency healing", "rife", "royal rife", "rife machine",
        "rife frequency", "cancer cure", "cancer treatment",
        "tumor", "oncology", "cancer therapy", "cancer research",
        "budesonide", "covid treatment", "covid prevention",
        "hcq", "hydroxychloroquine", "ivermectin", "suramin",
        "mebendazole", "fenbendazole", "diclacet", "dichloroacetate",
        "sodium dichloroacetate", "dca", "antineoplastic",
        "antiviral", "antibacterial", "antimicrobial",
        "antioxidant", "oxidative", "ozone", "ozone therapy",
        "oxidative therapy", "peroxide", "hydrogen peroxide",
        "chlorine dioxide", "cds", "mms", "sodium chlorite",
        "scenar", "tens", "microcurrent", "electrotherapy",
        "frequency", "resonance therapy", "energy medicine",
        "vibrational medicine", "sound therapy", "music therapy",
        "light therapy", "color therapy", "chromotherapy"],
    "Agriculture": ["agriculture", "farming", "permaculture", "soil",
        "compost", "biodynamic", "organic farming", "crop", "plant",
        "garden", "seed", "mycelium", "mushroom", "vermicompost",
        "biochar", "terra preta", "agroecology", "regenerative",
        "food forest", "polyculture", "companion plant", "cover crop",
        "mulch", "swale", "hugelkultur", "duckweed", "aquaculture",
        "aeroponics", "hydroponics", "aquaponics", "spirulina",
        "algae", "biofertilizer", "compost tea", "effective microorganism",
        "em ", "em1", "em-1", "mycorrhiza", "mycorrhizal",
        "rhizobia", "nitrogen fixation", "nitrogen fix",
        "cover crop", "green manure", "biochar", "agroforestry",
        "permaculture", "keyline", "yeomans", "holistic management",
        "regenerative agriculture", "carbon farming", "soil health",
        "soil microbiome", "compost", "vermicompost", "worm",
        "vermiculture", "worm castings", "compost"],
    "Chemistry": ["chemistry", "chemical", "reaction", "element",
        "isotope", "transmutation", "alchemy", "spagyric",
        "ormus", "orme", "monatomic", "colloidal", "catalyst",
        "oxidation", "reduction", "molecule", "compound", "synthesis",
        "electrolysis", "acid", "alkaline", "salt", "mineral",
        "biochemical", "tetracopper", "kanzius", "siloxene",
        "kautsky", "silver", "colloidal silver", "colloidal gold",
        "colloidal copper", "tetrasilver", "tetra silver",
        "silver tetraoxide", "ag4o4", "nanosilver", "nano silver",
        "colloidal", "suspension", "precipitate", "solution",
        "solvent", "reagent", "catalyst", "polymer", "monomer",
        "resin", "epoxy", "polyurethane", "silicone", "silane",
        "siloxene", "silicone", "silicon", "silica", "quartz",
        "zeolite", "clay", "bentonite", "kaolin", "porcelain"],
    "Material Sciences": ["material", "crystal", "crystallography",
        "semiconductor", "superconductor", "nanomaterial", "graphene",
        "metamaterial", "alloy", "metallurgy", "ceramic", "polymer",
        "composite", "nanotube", "fullerene", "buckminster",
        "buckyball", "quantum dot", "thin film", "lattice",
        "crystalline", "quasicrystal", "nanoparticle", "nanoplate",
        "nanosheet", "nanoflower", "nanowire", "nanorod",
        "2d material", "2d-material", "mos2", "molybdenum",
        "graphene oxide", "go ", "reduced go", "rgo",
        "carbon nanotube", "cnt", "carbon", "diamond",
        "boron", "boron nitride", "bn ", "hexagonal boron",
        "perovskite", "solar cell", "photovoltaic", "pv ",
        "battery", "lithium", "li-ion", "li ion", "supercapacitor",
        "capacitor", "dielectric", "ferroelectric", "piezoelectric",
        "electrostrictive", "magnetostrictive", "shape memory",
        "nitinol", "smart material", "metamaterial",
        "photonic crystal", "phononic crystal", "acoustic metamaterial"],
    "Geometry": ["geometry", "sacred geometry", "proportion",
        "golden ratio", "phi", "fibonacci", "fractal",
        "platonic solid", "polyhedra", "tesselation", "pattern",
        "symmetry", "vesica", "flower of life", "metatron",
        "merkaba", "spiral", "helix", "torus", "vortex",
        "mathematics", "topology", "projective", "counter-space",
        "chestahedron", "sri yantra", "sriyantra", "yantra",
        "mandala", "sacred", "geometric", "proportion",
        "harmonic", "harmonics", "ratio", "resonant",
        "form", "morphology", "pattern"],
    "Crystals": ["crystal", "quartz", "piezoelectric", "crystallography",
        "lattice", "mineral", "gem", "amethyst", "tourmaline",
        "selenite", "shungite", "orgonite", "crystal skull",
        "crystal grid", "crystal healing", "gemstone", "diamond",
        "crystal", "crystalline", "monocrystal", "single crystal",
        "seed crystal", "crystal growth", "crystal structure"],
    "Transportation": ["vehicle", "engine", "propulsion", "thrust",
        "fuel", "transportation", "aviation", "aircraft", "ship",
        "diesel", "gasoline", "electric vehicle", "fuel cell",
        "hydrogen", "biodiesel", "turbo", "jet", "rocket",
        "spaceship", "drone", "motor", "combustion", "steam",
        "stirling", "carburetor", "vapor", "vaporize", "vaporise",
        "mpg", "fuel efficiency", "hybrid", "ev ", "electric car",
        "boat", "marine", "submarine", "underwater", "diving",
        "bicycle", "unicycle", "gyrocar", "monorail", "train",
        "rail", "locomotive", "tram", "trolley",
        "airship", "blimp", "zeppelin", "dirigible", "balloon",
        "glider", "ornithopter", "flapping", "wing",
        "hovercraft", "ground effect", "ekranoplan",
        "propeller", "rotor", "turbine", "impeller",
        "wheel", "hub", "axle", "drive", "transmission",
        "gear", "chain", "belt", "pulley", "cam", "crank"],
    "Environmental": ["environment", "pollution", "climate", "geoengineering",
        "weather", "atmosphere", "ecosystem", "toxin", "radiation",
        "emf", "electromagnetic pollution", "geopathic", "earth energy",
        "ley line", "geomancy", "feng shui", "building biology",
        "electromagnetic field", "non-native emf", "5g", "wifi",
        "cell tower", "smart meter", "chemtrail", "haarp",
        "weather modification", "cloud seeding", "rain making",
        "dew", "dew pond", "dew harvest", "air well", "fog fence",
        "fog collection", "condensation", "water from air",
        "atmospheric water", "climate", "weather",
        "earth", "geology", "seismic", "earthquake",
        "volcano", "tectonic", "plate tectonics"],
    "Construction": ["construction", "building", "architecture",
        "dome", "vaastu", "sacred architecture", "geodesic",
        "timber", "straw bale", "cob", "hempcrete", "earthship",
        "passive house", "natural building", "green building",
        "sustainable", "biotecture", "pacific domes",
        "monolithic", "thin shell", "concrete", "canvas",
        "fabric structure", "tensile", "membrane",
        "nissen", "hut", "quonset", "barracks",
        "shelter", "housing", "home", "dwelling",
        "brick", "stone", "masonry", "adobe", "rammed earth",
        "timber frame", "post and beam", "log", "cabin"],
    "Time": ["time", "temporal", "chronology", "kozyrev",
        "torsion", "time dilation", "causality", "retrocausal",
        "entropy", "arrow of time", "cyclic", "rhythm",
        "oscillation", "frequency", "resonance", "harmonic",
        "synchronization", "swanson", "synchronized universe",
        "kozyrev", "torsion field", "time wave", "timewave",
        "novelty", "mckenna", "i ching", "timewave zero",
        "shnoll", "effect of time", "time physics"],
    "Life Force": ["life force", "orgone", "odic", "vril", "prana",
        "chi", "qi ", "subtle energy", "biodynamic", "biophotonic",
        "etheric", "vital force", "reich", "cloudbuster",
        "orgone accumulator", "bion", "deadly orgone", "dor",
        "cosmic orgone", "heliognosis", "orgone energy",
        "wilhelm reich", "reichian", "orgonomy", "orgone therapy",
        "vegetotherapy", "character armor", "muscular armor",
        "bioenergy", "bioenergetics", "lowen", "bioenergetic",
        "life energy", "vital energy", "vitalism", "vitalist",
        "elan vital", "bergson", "creative evolution",
        "entelechy", "driesch", "morphogenetic field",
        "sheldrake", "rupert sheldrake", "morphic resonance",
        "formative causation", "morphic", "morphogenetic"],
    "Suppression": ["suppression", "censorship", "conspiracy",
        "cover-up", "patent seizure", "suppressed invention",
        "fda", "epa", "classified", "secret", "black project",
        "military", "invention secrecy", "gag order", "banned",
        "forbidden", "lost invention", "seizure", "order 8550",
        "secrecy", "patent", "classified", "national security",
        "invention secrecy order", "secrecy order", "gag",
        "withdrawn", "banned", "forbidden", "lost",
        "suppressed", "censored", "censor", "coverup"],
    "Goethean Science": ["goethe", "goethean", "phenomenology",
        "morphology", "metamorphosis", "wholeness",
        "holistic science", "steiner", "anthroposoph",
        "waldorf", "biodynamic", "etheric", "astral",
        "consciousness soul", "thinking", "cognition",
        "holdrege", "talbott", "plant", "leaf",
        "metamorphosis of plants", "goethe science",
        "goethean science", "delicate empirical",
        "exact sense perception", "phenomenology of nature",
        "qualitative science", "wholistic", "holistic"],
    "Natural Philosophy": ["philosophy", "epistemology", "ontology",
        "nondual", "dualism", "materialism", "reductionism",
        "paradigm", "kant", "cartesian", "post-modern",
        "rational", "empirical", "qualia", "qualitative",
        "holism", "systems", "complexity", "emergence",
        "morrison", "metaphysics", "cosmology",
        "natural philosophy", "philosophy of science",
        "philosophy of nature", "epistemology",
        "ontology", "phenomenology", "hermeneutics",
        "dialectic", "logic", "reason", "truth",
        "being", "existence", "reality", "nature",
        "cosmos", "universe", "creation", "origin"],
    "Language": ["language", "linguistics", "grammar", "trivium",
        "rhetoric", "dialectic", "semantics", "semiotics",
        "etymology", "phonetics", "syntax", "logos",
        "word", "meaning", "sign", "symbol",
        "communication", "speech", "writing", "text"],
    "Fallacies of Standard Model": ["standard model", "quantum mechanics",
        "relativity", "einstein", "newton", "big bang",
        "dark matter", "dark energy", "particle physics",
        "quantum field theory", "string theory", "supersymmetry",
        "higgs", "cern", "lhc", "fallacy", "wrong", "debunk",
        "standard model", "quantum", "qft", "quantum electrodynamics",
        "qed", "quantum chromodynamics", "qcd", "gauge theory",
        "yang mills", "higgs boson", "higgs field",
        "dark matter", "dark energy", "black hole",
        "singularity", "event horizon", "wormhole",
        "multiverse", "many worlds", "string theory",
        "m-theory", "brane", "calabi-yau", "extra dimensions"],
    "Transhumanism": ["transhumanism", "transhuman", "geoengineering",
        "chemtrail", "weather modification", "haarp", "5g",
        "surveillance", "mind control", "biometric", "microchip",
        "artificial intelligence", "technocracy", "digital id",
        "cbdc", "social credit", "internet of things",
        "nanotech", "nanoparticle", "mrna", "gene editing",
        "crispr", "gain of function", "covid", "vaccine",
        "transhuman", "posthuman", "cyborg", "bci",
        "brain computer", "neural implant", "neuralink",
        "deep brain stimulation", "dbs", "tms", "transcranial",
        "ect", "electroshock", "psychiatry", "psychotropic",
        "psychiatric drug", "antidepressant", "ssri",
        "antipsychotic", "neuroleptic", "stimulant",
        "adhd", "medication", "big pharma", "pharmaceutical",
        "medical industrial complex", "health care system",
        "medical system", "hospital", "clinic", "doctor",
        "physician", "surgeon", "surgery", "operation",
        "medical procedure", "medical device", "medical implant",
        "hip replacement", "knee replacement", "dental",
        "tooth", "teeth", "bone", "glue", "bone glue",
        "filling", "crown", "implant", "prosthetic",
        "artificial", "synthetic", "plastic", "polymer",
        "bioplastic", "biodegradable", "compostable"],
    "Borderland Research": ["borderland", "frontier science",
        "alternative science", "suppressed science",
        "unexplained", "anomalous", "fortean", "charles fort",
        "anomaly", "paranormal", "parapsychology",
        "unconventional", "fringe", "edge science",
        "anomalous", "anomaly", "phenomenon",
        "unexplained", "mysterious", "enigma",
        "paradox", "contradiction", "impossible",
        "improbable", "extraordinary", "remarkable",
        "astonishing", "surprising", "unexpected",
        "counterintuitive", "puzzling", "baffling"],
    "Renewable Energy": ["solar", "wind", "hydro", "geothermal",
        "biomass", "renewable", "sustainable", "clean energy",
        "photovoltaic", "battery", "fuel cell", "hydrogen",
        "biofuel", "algae", "stirling", "tidal", "wave energy",
        "thermoelectric", "solar panel", "solar cell",
        "solar thermal", "concentrating solar", "cpv",
        "perovskite solar", "dye sensitized", "dssc",
        "wind turbine", "windmill", "vertical axis",
        "savonius", "darrieus", "hawt", "vawt",
        "hydroelectric", "micro hydro", "pico hydro",
        "run of river", "tidal stream", "wave power",
        "ocean thermal", "otec", "salinity gradient",
        "osmotic power", "bioenergy", "biogas",
        "gasification", "pyrolysis", "torrefaction",
        "densification", "briquette", "pellet",
        "wood gas", "producer gas", "syngas",
        "cogeneration", "chp", "combined heat",
        "heat pump", "geothermal", "ground source",
        "heat pipe", "thermosyphon", "heat exchanger"],
}

# ─── Meta-categories ───
META_CATEGORIES = {
    "Aether, Light & Electricity": ["Aether Physics", "Light", "Magnetism", "Life Force"],
    "Plasma, Torsion & Cosmology": ["Electric Universe", "Time", "Gravity"],
    "Goethean & Anthroposophical Science": ["Goethean Science", "Natural Philosophy", "Language"],
    "Radionics, Radiesthesia & Shape Power": ["Psychotronics"],
    "Optics & Colour Therapy": ["Light", "Crystals"],
    "Biological & Morphogenetic Science": ["Biology", "Health Medicine", "Consciousness"],
    "Water Structure & Memory": ["Water", "Environmental"],
    "Sacred & Projective Geometry": ["Geometry", "Architecture", "Construction"],
    "Regenerative Agriculture": ["Agriculture"],
    "Material Sciences & Alchemy": ["Chemistry", "Material Sciences"],
    "Transhumanism & Psychotronic Warfare": ["Transhumanism", "Suppression"],
    "Energy & Transportation": ["Energy Generation", "Renewable Energy", "Transportation"],
    "Challenges to the Standard Model": ["Fallacies of Standard Model", "Borderland Research"],
    "Harmonics, Rhythms & Cycles": ["Geometry", "Time", "Crystals"],
    "Weather & Geo-Engineering": ["Environmental", "Transhumanism"],
}

# ─── Known folder name → category mappings (from v4b + new ones) ───
FOLDER_HINTS = {
    "meyerhy": ["Energy Generation", "Water"],
    "tetracopper": ["Chemistry", "Material Sciences"],
    "biophotons": ["Biology", "Light", "Consciousness"],
    "xtlradio": ["Aether Physics", "Light"],
    "sahnokurashov": ["Biology", "Chemistry"],
    "nairgraphene": ["Water", "Material Sciences"],
    "hurtubis": ["Aether Physics", "Borderland Research"],
    "HodowanecRhysmonics": ["Aether Physics", "Energy Generation"],
    "covidatabase": ["Health Medicine", "Transhumanism"],
    "fuchs": ["Biology", "Health Medicine"],
    "nanobubblegener": ["Water"],
    "usa": ["Borderland Research", "Suppression"],
    "ketchum": ["Energy Generation", "Transportation"],
    "aether": ["Aether Physics"],
    "energy": ["Energy Generation"],
    "water": ["Water"],
    "magnet": ["Magnetism"],
    "gravity": ["Gravity"],
    "tesla": ["Aether Physics", "Energy Generation"],
    "orgone": ["Life Force"],
    "reich": ["Life Force"],
    "schauberger": ["Water", "Energy Generation"],
    "pollack": ["Water"],
    "plasma": ["Electric Universe"],
    "radionics": ["Psychotronics"],
    "radiesthesia": ["Psychotronics"],
    "goethe": ["Goethean Science"],
    "steiner": ["Goethean Science"],
    "crystal": ["Crystals", "Material Sciences"],
    "light": ["Light"],
    "color": ["Light"],
    "colour": ["Light"],
    "health": ["Health Medicine"],
    "medicine": ["Health Medicine"],
    "cancer": ["Health Medicine"],
    "covid": ["Health Medicine", "Transhumanism"],
    "agriculture": ["Agriculture"],
    "farm": ["Agriculture"],
    "permaculture": ["Agriculture"],
    "chemistry": ["Chemistry"],
    "alchemy": ["Chemistry"],
    "ormus": ["Chemistry", "Life Force"],
    "material": ["Material Sciences"],
    "graphene": ["Material Sciences", "Water"],
    "nanotube": ["Material Sciences"],
    "geometry": ["Geometry"],
    "sacred": ["Geometry"],
    "transport": ["Transportation"],
    "engine": ["Transportation", "Energy Generation"],
    "motor": ["Transportation", "Energy Generation"],
    "fuel": ["Transportation", "Energy Generation"],
    "environment": ["Environmental"],
    "geoeng": ["Environmental", "Transhumanism"],
    "weather": ["Environmental"],
    "climate": ["Environmental"],
    "construction": ["Construction"],
    "architecture": ["Construction"],
    "dome": ["Construction"],
    "time": ["Time"],
    "kozyrev": ["Time"],
    "torsion": ["Time", "Aether Physics"],
    "scalar": ["Aether Physics"],
    "longitudinal": ["Aether Physics"],
    "consciousness": ["Consciousness"],
    "mind": ["Consciousness"],
    "psi": ["Consciousness"],
    "biology": ["Biology"],
    "dna": ["Biology"],
    "embryo": ["Biology"],
    "transmutation": ["Chemistry", "Biology"],
    "suppression": ["Suppression"],
    "fort": ["Borderland Research"],
    "borderland": ["Borderland Research"],
    "freeenergy": ["Energy Generation"],
    "free energy": ["Energy Generation"],
    "overunity": ["Energy Generation"],
    "zero": ["Aether Physics"],
    "vacuum": ["Aether Physics"],
    "fusion": ["Energy Generation"],
    "hydrogen": ["Energy Generation", "Water"],
    "solar": ["Renewable Energy", "Light"],
    "wind": ["Renewable Energy"],
    "battery": ["Renewable Energy"],
    "geothermal": ["Renewable Energy"],
    "transhuman": ["Transhumanism"],
    "haarp": ["Transhumanism", "Environmental"],
    "5g": ["Transhumanism", "Environmental"],
    "chemtrail": ["Transhumanism", "Environmental"],
    "vaccine": ["Health Medicine", "Transhumanism"],
    "rife": ["Health Medicine"],
    "frequency": ["Health Medicine", "Consciousness"],
    "healing": ["Health Medicine"],
    "emf": ["Environmental"],
    "geopathic": ["Environmental"],
    "ley": ["Environmental"],
    "dowsing": ["Psychotronics", "Environmental"],
    "biogeometry": ["Psychotronics", "Environmental"],
    "vaastu": ["Construction", "Geometry"],
    "vastu": ["Construction", "Geometry"],
    "fengshui": ["Environmental", "Construction"],
    "cymatics": ["Geometry", "Consciousness"],
    "harmonics": ["Geometry", "Time"],
    "sound": ["Consciousness", "Geometry"],
    "vibration": ["Consciousness"],
    "resonance": ["Aether Physics", "Consciousness"],
    "ether": ["Aether Physics"],
    "neurofeedback": ["Consciousness"],
    "brainwave": ["Consciousness"],
    "meditation": ["Consciousness"],
    "remote": ["Consciousness"],
    "telepathy": ["Consciousness"],
    "antigravity": ["Gravity"],
    "anti-gravity": ["Gravity"],
    "levitation": ["Gravity"],
    "propulsion": ["Transportation", "Gravity"],
    "ufo": ["Transportation", "Borderland Research"],
    "uap": ["Transportation", "Borderland Research"],
    "coldfusion": ["Energy Generation", "Chemistry"],
    "lenr": ["Energy Generation", "Chemistry"],
    "meyer": ["Energy Generation", "Water"],
    "moray": ["Energy Generation"],
    "hendershot": ["Energy Generation"],
    "searl": ["Energy Generation", "Magnetism"],
    "newman": ["Energy Generation"],
    "bedini": ["Energy Generation"],
    "rossi": ["Energy Generation", "Chemistry"],
    "papp": ["Energy Generation"],
    "perendev": ["Energy Generation", "Magnetism"],
    "godin": ["Gravity"],
    "roschin": ["Gravity"],
    "podkletnov": ["Gravity"],
    "tajmar": ["Gravity"],
    "brown": ["Gravity", "Aether Physics"],
    "biefeld": ["Gravity", "Aether Physics"],
    "lifter": ["Gravity", "Aether Physics"],
    "ion": ["Aether Physics", "Gravity"],
    "electrogravitic": ["Gravity", "Aether Physics"],
    "sperry": ["Aether Physics"],
    "royalrife": ["Health Medicine"],
    "nesara": ["Suppression"],
    "secrecy": ["Suppression"],
    "patent": ["Suppression"],
    "invention": ["Energy Generation"],
    "perpetual": ["Energy Generation"],
    "selfrunning": ["Energy Generation"],
    "fuelless": ["Energy Generation"],
    "kinetic": ["Energy Generation"],
    "thermodynamic": ["Energy Generation"],
    "entropy": ["Time", "Aether Physics"],
    "quantum": ["Aether Physics"],
    "wave": ["Aether Physics", "Light"],
    "field": ["Aether Physics"],
    "electric": ["Aether Physics"],
    "magnetic": ["Magnetism"],
    "gravit": ["Gravity"],
    "photon": ["Light"],
    "optic": ["Light"],
    "spectro": ["Light"],
    "therapy": ["Health Medicine"],
    "disease": ["Health Medicine"],
    "nutrition": ["Health Medicine", "Agriculture"],
    "herbal": ["Health Medicine", "Agriculture"],
    "homeopathy": ["Health Medicine"],
    "detox": ["Health Medicine"],
    "immune": ["Health Medicine"],
    "soil": ["Agriculture"],
    "compost": ["Agriculture"],
    "seed": ["Agriculture"],
    "plant": ["Agriculture", "Biology"],
    "garden": ["Agriculture"],
    "crop": ["Agriculture"],
    "biochar": ["Agriculture"],
    "mushroom": ["Agriculture", "Biology"],
    "fungi": ["Agriculture", "Biology"],
    "bacteria": ["Biology"],
    "virus": ["Biology", "Health Medicine"],
    "cell": ["Biology"],
    "gene": ["Biology"],
    "rna": ["Biology"],
    "evolution": ["Biology"],
    "epigenetic": ["Biology"],
    "stem": ["Biology"],
    "tissue": ["Biology"],
    "organ": ["Biology", "Health Medicine"],
    "quartz": ["Crystals"],
    "piezo": ["Crystals"],
    "mineral": ["Crystals", "Material Sciences"],
    "gem": ["Crystals"],
    "lattice": ["Crystals", "Material Sciences"],
    "semiconductor": ["Material Sciences"],
    "superconductor": ["Material Sciences"],
    "nanomaterial": ["Material Sciences"],
    "fullerene": ["Material Sciences"],
    "alloy": ["Material Sciences"],
    "polymer": ["Material Sciences"],
    "ceramic": ["Material Sciences"],
    "golden": ["Geometry"],
    "fibonacci": ["Geometry"],
    "fractal": ["Geometry"],
    "platonic": ["Geometry"],
    "vesica": ["Geometry"],
    "torus": ["Geometry", "Aether Physics"],
    "helix": ["Geometry", "Biology"],
    "spiral": ["Geometry", "Aether Physics"],
    "vehicle": ["Transportation"],
    "aviation": ["Transportation"],
    "aircraft": ["Transportation"],
    "rocket": ["Transportation"],
    "ship": ["Transportation"],
    "combustion": ["Transportation"],
    "steam": ["Transportation", "Energy Generation"],
    "stirling": ["Energy Generation", "Transportation"],
    "diesel": ["Transportation"],
    "gasoline": ["Transportation"],
    "pollution": ["Environmental"],
    "atmosphere": ["Environmental"],
    "ecosystem": ["Environmental"],
    "radiation": ["Environmental", "Health Medicine"],
    "building": ["Construction"],
    "hempcrete": ["Construction"],
    "cob": ["Construction"],
    "straw": ["Construction"],
    "timber": ["Construction"],
    "causality": ["Time"],
    "cyclic": ["Time"],
    "rhythm": ["Time"],
    "oscillation": ["Time", "Aether Physics"],
    "harmonic": ["Time", "Geometry"],
    "cloudbuster": ["Life Force", "Environmental"],
    "vril": ["Life Force"],
    "chi": ["Life Force"],
    "qi": ["Life Force"],
    "subtle": ["Life Force", "Aether Physics"],
    "vital": ["Life Force"],
    "etheric": ["Life Force", "Aether Physics"],
    "biophot": ["Life Force", "Light", "Biology"],
    "anthroposoph": ["Goethean Science"],
    "waldorf": ["Goethean Science"],
    "phenomenology": ["Goethean Science", "Natural Philosophy"],
    "morphology": ["Goethean Science", "Biology"],
    "philosophy": ["Natural Philosophy"],
    "epistemology": ["Natural Philosophy"],
    "ontology": ["Natural Philosophy"],
    "paradigm": ["Natural Philosophy"],
    "reductionism": ["Natural Philosophy", "Fallacies of Standard Model"],
    "materialism": ["Natural Philosophy", "Fallacies of Standard Model"],
    "einstein": ["Fallacies of Standard Model"],
    "relativity": ["Fallacies of Standard Model", "Gravity"],
    "standardmodel": ["Fallacies of Standard Model"],
    "darkmatter": ["Fallacies of Standard Model"],
    "darkenergy": ["Fallacies of Standard Model"],
    "bigbang": ["Fallacies of Standard Model", "Electric Universe"],
    "surveillance": ["Transhumanism"],
    "mindcontrol": ["Transhumanism", "Consciousness"],
    "microchip": ["Transhumanism"],
    "nanoparticle": ["Transhumanism", "Material Sciences"],
    "mrna": ["Transhumanism", "Health Medicine"],
    "crispr": ["Transhumanism", "Biology"],
    "anomaly": ["Borderland Research"],
    "paranormal": ["Borderland Research", "Consciousness"],
    "unexplained": ["Borderland Research"],
    "fringe": ["Borderland Research"],
    "photovoltaic": ["Renewable Energy"],
    "tidal": ["Renewable Energy"],
    "biomass": ["Renewable Energy", "Agriculture"],
    "hydro": ["Renewable Energy", "Water"],
    "language": ["Language"],
    "linguistics": ["Language"],
    "grammar": ["Language"],
    "trivium": ["Language"],
    # ─── NEW: folder names found in the unmapped analysis ───
    "airwellslibrary": ["Water", "Environmental"],
    "constantinescusonicity": ["Aether Physics", "Energy Generation"],
    "coandaeffect": ["Aether Physics", "Transportation"],
    "electroculture": ["Agriculture", "Aether Physics"],
    "kautskysiloxene": ["Chemistry", "Material Sciences"],
    "432a4": ["Consciousness", "Aether Physics"],
    "dragonflypatents": ["Transportation", "Gravity"],
    "ergonomicpillowpatents": ["Health Medicine", "Material Sciences"],
    "smithoudevices": ["Energy Generation", "Aether Physics"],
    "correa": ["Energy Generation", "Aether Physics"],
    "spirulina": ["Agriculture", "Biology"],
    "nomography": ["Geometry", "Natural Philosophy"],
    "wilkes": ["Transportation", "Material Sciences"],
    "nakamats": ["Energy Generation", "Borderland Research"],
    "kenyon": ["Energy Generation", "Aether Physics"],
    "flashjouleheating": ["Energy Generation", "Material Sciences"],
    "sullivan": ["Energy Generation", "Transportation"],
    "cohererpatents": ["Aether Physics", "Material Sciences"],
    "shoulders": ["Aether Physics", "Energy Generation"],
    "klein": ["Energy Generation", "Transportation"],
    "rabinowemclutch": ["Magnetism", "Transportation"],
    "whittakr": ["Aether Physics", "Light"],
    "schaub": ["Energy Generation"],
    "see": ["Aether Physics", "Light"],
    "ohmasa": ["Water", "Energy Generation"],
    "budesonide": ["Health Medicine"],
    "seike": ["Aether Physics", "Energy Generation", "Gravity"],
    "majorana": ["Aether Physics", "Gravity"],
    "marinovlibrary": ["Aether Physics", "Energy Generation"],
    "aho": ["Aether Physics", "Energy Generation"],
    "millsspacedrive": ["Gravity", "Transportation"],
    "antelmantsto": ["Chemistry", "Energy Generation"],
    "schwentt": ["Energy Generation", "Transportation"],
    "kervran": ["Biology", "Chemistry"],
    "hcquine": ["Health Medicine"],
    "maxwell2": ["Aether Physics", "Light"],
    "dirckspm": ["Gravity", "Transportation"],
    "earthradio": ["Aether Physics", "Electric Universe"],
    "peroxide": ["Health Medicine", "Chemistry"],
    "bendallplasmoid": ["Aether Physics", "Electric Universe"],
    "xianfengboneglue": ["Health Medicine", "Material Sciences"],
    "anaestheticssyntheses": ["Health Medicine", "Chemistry"],
    "ecklin": ["Energy Generation", "Magnetism"],
    "holcombernergysystem": ["Energy Generation", "Magnetism"],
    "milewski": ["Chemistry", "Material Sciences"],
    "chukanov": ["Aether Physics", "Energy Generation"],
    "husuperwood": ["Material Sciences"],
    "aeroponics": ["Agriculture"],
    "cannabis": ["Agriculture", "Health Medicine"],
    "hdac1": ["Health Medicine", "Biology"],
    "vallee": ["Consciousness", "Borderland Research"],
    "infolios": ["Natural Philosophy", "Language"],
    "mos2nanoflowers": ["Material Sciences"],
    "melnichenkoferromag": ["Magnetism", "Material Sciences"],
    "keelyhz": ["Aether Physics", "Consciousness"],
    "smith": ["Energy Generation"],
    "pantone": ["Energy Generation", "Transportation"],
    "santilli2": ["Aether Physics", "Chemistry"],
    "karrick2": ["Energy Generation", "Environmental"],
    "nissenhut": ["Construction"],
    "gyrocar": ["Transportation", "Gravity"],
    "bostickplasmoids": ["Electric Universe", "Aether Physics"],
    "constantinesco2": ["Aether Physics", "Transportation"],
    "meylscalar": ["Aether Physics", "Energy Generation"],
    "zuccarelliholophonics": ["Consciousness", "Light"],
    "gajarevpatents": ["Health Medicine"],
    "yater": ["Energy Generation", "Aether Physics"],
    "fancoal": ["Energy Generation", "Environmental"],
    "biolocation": ["Psychotronics", "Environmental"],
    "kilner": ["Light", "Consciousness"],
    "sweet2": ["Energy Generation", "Magnetism"],
    "egelyenergyamplifier": ["Energy Generation", "Life Force"],
    "stockman": ["Energy Generation"],
    "teslacospr": ["Health Medicine", "Aether Physics"],
    "nelsonarticles": ["Energy Generation", "Aether Physics"],
    "araquemicrowavedrill": ["Energy Generation", "Material Sciences"],
    "xingbaticacatoothpaste": ["Health Medicine", "Material Sciences"],
    "ide": ["Energy Generation"],
    "piccardi": ["Biology", "Cosmology"],
    "scenar": ["Health Medicine"],
    "survival": ["Borderland Research", "Environmental"],
    "perrigo": ["Energy Generation"],
    "trumpesmtr": ["Energy Generation", "Aether Physics"],
    "prophist": ["Natural Philosophy"],
    "plans": ["Construction"],
    "golod": ["Energy Generation", "Aether Physics"],
    "koeneman": ["Health Medicine"],
    "pearson": ["Energy Generation"],
    "carr": ["Energy Generation", "Transportation"],
    "apeelpreserv": ["Agriculture", "Material Sciences"],
    "ighina2": ["Aether Physics", "Life Force"],
    "gogins": ["Energy Generation"],
    "liquidpiston": ["Transportation", "Energy Generation"],
    "milkovic": ["Gravity", "Energy Generation"],
    "kaznachv": ["Consciousness", "Biology"],
    "kutienkov": ["Energy Generation"],
    "aquino": ["Energy Generation", "Aether Physics"],
    "tripler": ["Energy Generation", "Aether Physics"],
    "quantregen": ["Energy Generation", "Consciousness"],
    "mccowenionpowergroup": ["Energy Generation", "Aether Physics"],
    "coler": ["Energy Generation", "Aether Physics"],
    "vlachos2": ["Health Medicine"],
    "white": ["Aether Physics"],
    "dean2": ["Energy Generation", "Gravity"],
    "sweet": ["Energy Generation", "Magnetism"],
    "naviauxsuramin": ["Health Medicine"],
    "perpmtnj": ["Energy Generation"],
    "brooks": ["Energy Generation"],
    "usa101": ["Suppression", "Borderland Research"],
    "teslamt": ["Aether Physics", "Energy Generation"],
    "schaub2": ["Energy Generation"],
    "bioecon": ["Agriculture", "Environmental"],
    "klinfogl": ["Aether Physics", "Light"],
    "agro2": ["Agriculture"],
    "bradshawinventwood": ["Material Sciences", "Construction"],
    "papinrouillygyropter": ["Transportation", "Gravity"],
    "dewharvest": ["Water", "Environmental"],
    "crossbow": ["Transportation"],
    "norris": ["Energy Generation"],
    "agplntbrdg": ["Agriculture"],
    "forwardstatite": ["Gravity", "Transportation"],
    "weigandwire": ["Aether Physics", "Energy Generation"],
    "merkl": ["Health Medicine", "Aether Physics"],
    "hhist": ["Borderland Research"],
    "kasmer": ["Energy Generation"],
    "circeo": ["Energy Generation"],
    "montagnierhomeop": ["Health Medicine", "Biology"],
    "barbosa": ["Energy Generation", "Aether Physics"],
    "kanarev2": ["Energy Generation", "Aether Physics"],
    "blomgren": ["Energy Generation"],
    "cyclogyro": ["Transportation", "Gravity"],
    "brandt": ["Health Medicine"],
    "bennett": ["Energy Generation"],
    "alperenturxotor": ["Transportation", "Energy Generation"],
    "kladovactivator": ["Energy Generation"],
    "tennantscenarbiomodulator": ["Health Medicine"],
    "gainsmicapaper": ["Material Sciences"],
    "laurent": ["Energy Generation"],
    "benitezbattycharg": ["Energy Generation", "Aether Physics"],
    "holtzapl": ["Energy Generation", "Aether Physics"],
    "birthcontrol": ["Health Medicine"],
    "makhonine": ["Transportation", "Energy Generation"],
    "dudley": ["Energy Generation"],
    "shakhparanov": ["Aether Physics"],
    "cherry": ["Environmental", "Health Medicine"],
    "cooleyfusion": ["Energy Generation", "Chemistry"],
    "teslatur": ["Aether Physics", "Energy Generation"],
    "trawoeger": ["Energy Generation"],
    "lyngstadaas": ["Material Sciences", "Health Medicine"],
    "mohorn": ["Energy Generation"],
    "stone": ["Construction", "Material Sciences"],
    "auto2": ["Transportation"],
    "testatik": ["Energy Generation"],
    "keshe": ["Energy Generation", "Aether Physics"],
    "rosseyeraydetector": ["Aether Physics", "Light"],
    "lapoint": ["Energy Generation", "Magnetism"],
    "sinclair": ["Energy Generation"],
    "stoneferrock": ["Construction", "Material Sciences"],
    "newnham": ["Material Sciences"],
    "holmesgyr": ["Transportation", "Gravity"],
    "hooper": ["Gravity", "Aether Physics"],
    "plauson": ["Energy Generation", "Aether Physics"],
    "deland": ["Energy Generation"],
    "brennangyromonorail": ["Transportation", "Gravity"],
    "curry": ["Health Medicine", "Environmental"],
    "bourke": ["Transportation", "Energy Generation"],
    "paispatents": ["Energy Generation", "Aether Physics"],
    "sriyantra": ["Geometry", "Consciousness"],
    "tetrasilver": ["Chemistry", "Material Sciences"],
    "brown5": ["Gravity", "Aether Physics"],
    "fogaltransistor": ["Aether Physics", "Material Sciences"],
    "keely": ["Aether Physics", "Consciousness"],
    "maxwell1": ["Aether Physics", "Light"],
    "champion": ["Transportation", "Energy Generation"],
    "negre": ["Transportation", "Energy Generation"],
    "cohex": ["Energy Generation"],
    "zadgnkar": ["Energy Generation"],
    "kindrvch": ["Energy Generation"],
    "pietro": ["Energy Generation"],
    "liciar": ["Energy Generation"],
    "ehrenhaf": ["Gravity", "Aether Physics"],
    "schaefferb": ["Energy Generation"],
    "besler": ["Transportation", "Energy Generation"],
    "amarasingham": ["Energy Generation"],
    "maglich": ["Energy Generation", "Chemistry"],
    "eckart": ["Energy Generation"],
    "sargoytchev": ["Energy Generation"],
    "baylinrotary": ["Transportation", "Energy Generation"],
    "vialle": ["Energy Generation"],
    "powerswim": ["Transportation"],
    "hallcowling": ["Energy Generation"],
    "andersonbeehive": ["Construction", "Agriculture"],
    "monstein": ["Aether Physics", "Electric Universe"],
    "vaideanu": ["Energy Generation"],
    "davidson": ["Energy Generation"],
    "diclacet": ["Health Medicine"],
    "nara": ["Energy Generation"],
    "biogeom": ["Environmental", "Psychotronics"],
    "comelladultstmcel": ["Energy Generation"],
    "egely": ["Energy Generation", "Life Force"],
    "rougeairfoil": ["Transportation"],
    "nakanishi": ["Energy Generation"],
    "grander": ["Water", "Life Force"],
    "walston": ["Energy Generation"],
    "wankelzischboat": ["Transportation", "Energy Generation"],
    "puyuellogdiode": ["Aether Physics", "Energy Generation"],
    "karpen": ["Energy Generation"],
    "lame": ["Energy Generation"],
    "fukushimamour": ["Environmental", "Health Medicine"],
    "gary": ["Energy Generation"],
    "rota2": ["Energy Generation", "Aether Physics"],
    "crile": ["Health Medicine", "Biology"],
    "grinmatth": ["Energy Generation"],
    "kahne": ["Energy Generation"],
    "coandaerotube": ["Transportation", "Aether Physics"],
    "wallace": ["Energy Generation"],
    "toll": ["Transportation"],
    "moradmutato": ["Biology", "Chemistry"],
    "miyamotopet": ["Health Medicine"],
    "vigier": ["Aether Physics", "Natural Philosophy"],
    "kanadycap": ["Energy Generation"],
    "hettinger": ["Energy Generation"],
    "huston": ["Energy Generation"],
    "fishcarb": ["Chemistry", "Material Sciences"],
    "milewskigold": ["Chemistry", "Material Sciences"],
    "bascle": ["Energy Generation"],
    "ev": ["Transportation"],
    "swartzmoxyfusion": ["Energy Generation", "Chemistry"],
    "nelson": ["Energy Generation"],
    "larsenau": ["Energy Generation"],
    "clynsens": ["Chemistry", "Environmental"],
    "mebendazole": ["Health Medicine"],
    "moraru": ["Energy Generation"],
    "stubblefield": ["Energy Generation", "Aether Physics"],
    "amplituhedron": ["Aether Physics", "Geometry"],
    "degeusboron": ["Chemistry", "Energy Generation"],
    "teslacar": ["Transportation", "Aether Physics"],
    "dean": ["Energy Generation", "Gravity"],
    "markstpu": ["Energy Generation"],
    "suratt": ["Energy Generation"],
    "fetta": ["Energy Generation", "Chemistry"],
    "york": ["Energy Generation", "Aether Physics"],
    "kamen": ["Transportation", "Energy Generation"],
    "brasher": ["Energy Generation"],
    "alxandr": ["Energy Generation"],
    "santilli": ["Aether Physics", "Chemistry"],
    "plummercave": ["Construction"],
    "chernetskii": ["Energy Generation", "Aether Physics"],
    "atp": ["Biology", "Energy Generation"],
    "adept": ["Energy Generation"],
    "aetzi": ["Energy Generation"],
    "aero": ["Transportation"],
    "aero2": ["Transportation"],
    "ito": ["Energy Generation"],
    "savaprionrx": ["Health Medicine"],
    "trofimov": ["Consciousness", "Biology"],
    "summers": ["Energy Generation"],
    "balasingham": ["Energy Generation"],
    "lang": ["Language"],
    "royfertilizer": ["Agriculture"],
    "starck": ["Energy Generation"],
    "abolafia": ["Energy Generation"],
    "o": ["Energy Generation"],
    "leenanoporeairwell": ["Water", "Material Sciences"],
    "angelo": ["Energy Generation"],
    "artemis": ["Aether Physics"],
    "hillprop": ["Energy Generation"],
    "gill": ["Energy Generation"],
    "platen": ["Energy Generation"],
    "momendryer": ["Energy Generation"],
    "robinson": ["Energy Generation"],
    "wainwright": ["Energy Generation"],
    "boycehho": ["Energy Generation", "Water"],
    "zinncomb": ["Energy Generation"],
    "filardotravwaveprop": ["Aether Physics"],
    "plichtasilane": ["Chemistry", "Material Sciences"],
    "violet": ["Light", "Consciousness"],
    "nordenstrom": ["Health Medicine"],
    "staver": ["Energy Generation"],
    "bodner": ["Energy Generation", "Gravity"],
    "platzglider": ["Transportation", "Aether Physics"],
    "sharma": ["Energy Generation"],
    "lithification": ["Construction", "Material Sciences"],
    "ebner2": ["Energy Generation"],
    "icedam": ["Environmental"],
    "markov": ["Energy Generation"],
    "lovellmonothermal": ["Energy Generation"],
    "naessens": ["Health Medicine", "Biology"],
    "axford": ["Energy Generation"],
    "hemp2": ["Construction", "Agriculture"],
    "catnip": ["Agriculture", "Health Medicine"],
    "chasematterwavebeam": ["Aether Physics"],
    "leavell": ["Energy Generation"],
    "pogue": ["Transportation", "Energy Generation"],
    "russeyeraydetector": ["Aether Physics", "Light"],
    "feg": ["Energy Generation"],
    "qinetiq": ["Energy Generation", "Transportation"],
    "clearsign": ["Energy Generation"],
    "wang": ["Energy Generation"],
    "coanda": ["Transportation", "Aether Physics"],
    "baneasa": ["Transportation"],
    "crocodile": ["Transportation"],
    "cuinanoagwire": ["Aether Physics", "Material Sciences"],
    "dandelion": ["Agriculture", "Health Medicine"],
    "brown-haley": ["Energy Generation"],
    "zurovcik": ["Energy Generation"],
    "djurek": ["Energy Generation"],
    "cynar": ["Agriculture"],
    "dobler": ["Energy Generation"],
    "wagnerzorongen": ["Energy Generation"],
    "dewpond": ["Water", "Environmental"],
    "serogodsky": ["Psychotronics", "Environmental"],
    "tobinick": ["Health Medicine"],
    "judd": ["Energy Generation"],
    "leimer": ["Energy Generation"],
    "rao": ["Energy Generation"],
    "mals": ["Energy Generation"],
    "ebola": ["Health Medicine"],
    "lanier": ["Energy Generation"],
    "linacre": ["Water", "Environmental"],
    "farrow": ["Energy Generation"],
    "nemes": ["Energy Generation"],
    "gunnrman": ["Energy Generation"],
    "hclcleantech": ["Environmental", "Chemistry"],
    "berl": ["Energy Generation"],
    "unibladeprop": ["Transportation", "Energy Generation"],
    "tamburini": ["Aether Physics"],
    "sweet3": ["Energy Generation", "Magnetism"],
    "foldscope": ["Material Sciences", "Biology"],
    "whalewing": ["Transportation"],
    "luling": ["Energy Generation"],
    "flanagan": ["Health Medicine", "Aether Physics"],
    "eden": ["Agriculture"],
    "posner": ["Energy Generation"],
    "arlinskichr": ["Energy Generation"],
    "ohsawa": ["Health Medicine"],
    "piggott": ["Energy Generation", "Aether Physics"],
    "lakhov": ["Energy Generation", "Aether Physics"],
    "rowley": ["Energy Generation"],
    "mouroutransmutn": ["Chemistry", "Energy Generation"],
    "dotto": ["Energy Generation", "Aether Physics"],
    "bartholomew": ["Energy Generation"],
    "thompson": ["Energy Generation"],
    "glubb": ["Energy Generation"],
    "jamison": ["Energy Generation"],
    "chausovsky": ["Energy Generation"],
    "sancoff": ["Health Medicine"],
    "dyke": ["Energy Generation"],
    "hartshorne": ["Energy Generation"],
    "blau": ["Energy Generation"],
    "helmholtz": ["Aether Physics", "Energy Generation"],
    "plauson2": ["Energy Generation", "Aether Physics"],
    "schubartneutrinov": ["Aether Physics"],
    "holubowicz": ["Energy Generation"],
    "barkernozzle": ["Transportation", "Energy Generation"],
    "johnson": ["Energy Generation"],
    "hurwich": ["Energy Generation"],
    "griffin": ["Energy Generation"],
    "hypnosis": ["Consciousness"],
    "malaria": ["Health Medicine"],
    "istrate": ["Energy Generation"],
    "tarakcioglu": ["Energy Generation"],
    "joisonochemhho": ["Energy Generation", "Chemistry"],
    "kimpprmuscl": ["Health Medicine"],
    "bare": ["Energy Generation"],
    "cornwell": ["Energy Generation"],
    "irving": ["Energy Generation"],
    "meng": ["Energy Generation"],
    "pikulmetalwood": ["Material Sciences"],
    "cook-magn": ["Magnetism", "Energy Generation"],
    "jefimenko": ["Aether Physics", "Energy Generation"],
    "christie": ["Energy Generation"],
    "gilmartin": ["Energy Generation"],
    "stclair": ["Energy Generation", "Aether Physics"],
    "perez": ["Energy Generation"],
    "delouise": ["Energy Generation"],
    "hiddink": ["Energy Generation"],
    "mizuno": ["Energy Generation", "Chemistry"],
    "bovis": ["Psychotronics", "Environmental"],
    "kent": ["Energy Generation"],
    "kellogg": ["Energy Generation"],
    "karnoukhovakula": ["Energy Generation"],
    "kita": ["Energy Generation"],
    "giapisco2ox": ["Chemistry", "Environmental"],
    "korovyakov": ["Energy Generation"],
    "kowsky": ["Gravity", "Aether Physics"],
    "ford": ["Transportation"],
    "karrick": ["Energy Generation", "Environmental"],
    "smeshgear": ["Transportation", "Energy Generation"],
    "transparentwood": ["Material Sciences"],
    "johnsonliairbatty": ["Energy Generation"],
    "montagnier": ["Health Medicine", "Biology"],
    "lucidream": ["Consciousness"],
    "cademartiri": ["Material Sciences"],
    "pellariniairtruk": ["Transportation"],
    "malgarini": ["Transportation"],
    "matveev": ["Energy Generation"],
    "xfldant": ["Energy Generation"],
    "sarikayatoothremin": ["Health Medicine", "Material Sciences"],
    "kohnen": ["Energy Generation"],
    "mielke": ["Energy Generation"],
    "toroidprop": ["Transportation", "Energy Generation"],
    "kuehnelhydrplastic": ["Material Sciences", "Energy Generation"],
    "oralift": ["Health Medicine"],
    "nassikas": ["Energy Generation", "Aether Physics"],
    "ballrope": ["Energy Generation"],
    "keplinger": ["Energy Generation"],
    "teslamos": ["Aether Physics", "Energy Generation"],
    "mueller": ["Energy Generation"],
    "alcantar": ["Material Sciences"],
    "nostrjih": ["Consciousness", "Borderland Research"],
    "gritskevich": ["Energy Generation"],
    "korschelt": ["Energy Generation"],
    "mohr": ["Energy Generation"],
    "plastic": ["Material Sciences"],
    "palti": ["Health Medicine"],
    "lippsprop": ["Transportation", "Energy Generation"],
    "nucell": ["Energy Generation"],
    "savagecsa25": ["Energy Generation"],
    "wurzburger": ["Energy Generation"],
    "kanarev": ["Energy Generation", "Aether Physics"],
    "pleiadesembassy": ["Consciousness", "Borderland Research"],
    "kamat": ["Energy Generation"],
    "nutsedge": ["Agriculture"],
    "sedwickring": ["Energy Generation"],
    "chlorinedioxide": ["Health Medicine", "Chemistry"],
    "magncellulose": ["Material Sciences"],
    "palmerd3o": ["Material Sciences"],
    "vincent": ["Energy Generation"],
    "asianpro": ["Energy Generation"],
    "cuppetilli": ["Energy Generation"],
    "nelsonfins": ["Energy Generation"],
    "hinewav": ["Energy Generation"],
    "hattongroove": ["Transportation", "Energy Generation"],
    "yangradicold": ["Energy Generation"],
    "ainslie": ["Energy Generation"],
    "grebenn": ["Energy Generation"],
    "dunaevskij": ["Energy Generation"],
    "santillilens": ["Aether Physics", "Light"],
    "ruhmkorffcoils": ["Aether Physics", "Energy Generation"],
    "sangblad": ["Energy Generation"],
    "chhatre": ["Agriculture"],
    "hontsu": ["Energy Generation"],
    "supercavitation": ["Transportation"],
    "waldinwaves": ["Aether Physics"],
    "avramenk": ["Energy Generation"],
    "lindsey": ["Energy Generation"],
    "durnin": ["Energy Generation"],
    "aidasupramolecularplastic": ["Material Sciences"],
    "dental": ["Health Medicine"],
    "keyline": ["Agriculture"],
    "allen": ["Energy Generation"],
    "brown4": ["Gravity", "Aether Physics"],
    "brown2": ["Gravity", "Aether Physics"],
    "brown1": ["Gravity", "Aether Physics"],
    "koh": ["Energy Generation"],
    "kollars": ["Energy Generation"],
    "bellocq": ["Energy Generation"],
    "unicycle": ["Transportation"],
    "adamsuspn": ["Transportation"],
    "boyette": ["Energy Generation"],
    "maisotsenko": ["Energy Generation", "Environmental"],
    "auto": ["Transportation"],
    "mary": ["Energy Generation"],
    "rubtsov": ["Aether Physics"],
    "krummenacher": ["Energy Generation"],
    "tiller": ["Energy Generation", "Aether Physics"],
    "wilks": ["Energy Generation"],
    "concrcanvas": ["Construction"],
    "davidovitch": ["Energy Generation"],
    "ziaie": ["Energy Generation"],
    "badash": ["Energy Generation"],
}


def match_categories(text, keywords_map):
    """Match text against category keywords, return sorted list of (category, score)."""
    text_lower = text.lower()
    scores = {}
    for cat, keywords in keywords_map.items():
        for kw in keywords:
            if kw in text_lower:
                if cat not in scores:
                    scores[cat] = 0
                scores[cat] += 1
    # Sort by score descending
    sorted_cats = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    return [cat for cat, score in sorted_cats[:5]]


def get_meta_categories(categories):
    """Map categories to meta-categories."""
    meta_cats = []
    for meta, sub_cats in META_CATEGORIES.items():
        for cat in categories:
            if cat in sub_cats and meta not in meta_cats:
                meta_cats.append(meta)
    return meta_cats


def extract_folder(url):
    """Extract rexresearch.com folder name from URL."""
    if 'rexresearch.com/' in url:
        parts = url.split('rexresearch.com/')[1].split('/')
        if len(parts) >= 2:
            return parts[0]
    return None


def main():
    print("Loading index.json...")
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    print(f"Loaded {len(data)} entries")

    # Collect folder info for auto-categorization
    folder_info = {}  # folder -> {titles: [], filenames: []}
    for entry in data:
        folder = extract_folder(entry.get('source_url', ''))
        if folder:
            if folder not in folder_info:
                folder_info[folder] = {'titles': [], 'filenames': [], 'previews': []}
            title = entry.get('title', '') or entry.get('filename', '')
            folder_info[folder]['titles'].append(title)
            folder_info[folder]['filenames'].append(entry.get('filename', ''))
            preview = entry.get('content_preview', '')
            if preview:
                folder_info[folder]['previews'].append(preview)

    # Auto-categorize unmapped folders
    auto_folder_map = {}
    for folder, info in folder_info.items():
        if folder.lower() in FOLDER_HINTS:
            auto_folder_map[folder] = FOLDER_HINTS[folder.lower()]
            continue

        # Build text from folder name + titles + filenames + previews
        text = folder + ' ' + ' '.join(info['titles'][:20]) + ' ' + ' '.join(info['filenames'][:20])
        if info['previews']:
            text += ' ' + ' '.join(info['previews'][:10])

        cats = match_categories(text, CATEGORY_KEYWORDS)
        if cats:
            auto_folder_map[folder] = cats

    print(f"Auto-categorized {len(auto_folder_map)} / {len(folder_info)} folders")

    # Now re-categorize all entries
    updated = 0
    for entry in data:
        folder = extract_folder(entry.get('source_url', ''))

        # Start with existing categories
        existing_cats = entry.get('categories', [])
        new_cats = list(existing_cats) if existing_cats else []

        # If no existing categories, try folder mapping
        if not new_cats and folder and folder.lower() in auto_folder_map:
            new_cats = auto_folder_map[folder.lower()]

        # If still no categories, try content-based matching
        if not new_cats:
            text = (entry.get('title', '') + ' ' + entry.get('filename', '') + ' ' + entry.get('content_preview', ''))
            new_cats = match_categories(text, CATEGORY_KEYWORDS)

        # If still no categories but folder exists, try folder name keyword match
        if not new_cats and folder:
            new_cats = match_categories(folder, CATEGORY_KEYWORDS)

        if new_cats and new_cats != existing_cats:
            entry['categories'] = new_cats
            entry['meta_categories'] = get_meta_categories(new_cats)
            updated += 1
        elif new_cats and not entry.get('meta_categories'):
            entry['meta_categories'] = get_meta_categories(new_cats)
            updated += 1

    print(f"Updated {updated} entries")

    # Write output
    print("Writing index.json...")
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, separators=(',', ':'))

    # Stats
    with_cats = sum(1 for e in data if e.get('categories'))
    with_meta = sum(1 for e in data if e.get('meta_categories'))
    with_patents = sum(1 for e in data if e.get('patent_numbers'))
    with_person = sum(1 for e in data if e.get('primary_person'))
    with_preview = sum(1 for e in data if len(e.get('content_preview', '')) > 20)
    with_url = sum(1 for e in data if e.get('source_url'))

    print()
    print("=== FINAL INDEX STATISTICS ===")
    print(f"Total files: {len(data)}")
    print(f"With categories: {with_cats} ({with_cats/len(data)*100:.1f}%)")
    print(f"Uncategorized: {len(data) - with_cats} ({(len(data) - with_cats)/len(data)*100:.1f}%)")
    print(f"With meta-categories: {with_meta}")
    print(f"With patent numbers: {with_patents}")
    print(f"With researcher name: {with_person}")
    print(f"With content preview: {with_preview}")
    print(f"With source URL: {with_url}")

    # Category counts
    cat_counts = {}
    for entry in data:
        for cat in entry.get('categories', []):
            cat_counts[cat] = cat_counts.get(cat, 0) + 1

    print()
    print("=== CATEGORY COUNTS ===")
    for cat, count in sorted(cat_counts.items(), key=lambda x: x[1], reverse=True):
        print(f"  {count:4d}  {cat}")

    # Meta-category counts
    meta_counts = {}
    for entry in data:
        for mc in entry.get('meta_categories', []):
            meta_counts[mc] = meta_counts.get(mc, 0) + 1

    print()
    print("=== META-CATEGORY COUNTS ===")
    for mc, count in sorted(meta_counts.items(), key=lambda x: x[1], reverse=True):
        print(f"  {count:4d}  {mc}")

    print()
    print("Done!")


if __name__ == '__main__':
    main()
