#!/usr/bin/env python3
"""QC 2026-10-04: add 20 feed works (10-03/10-04 batches) missing from research-index,
plus 17 new persons. Additive only; no existing entries modified."""
import json

WORKS = [
    {"id":"reich-geiger-mueller-oranur-harrer-de","title":"Bernhard Harrer — Reichs Arbeit mit dem Geiger-Müller-Zähler: Lebensenergie und Radioaktivität im 'Oranur-Experiment' (de→EN)","authors":["bernhard-harrer"],"date":"2026-10-04","language":"de","translated":True,"file":"translations/2026-10-04-reich-geiger-mueller-oranur-harrer-de.md","themes":["Aether, Light & Electricity","Consciousness & Subtle Energy"],"concepts":["Wilhelm Reich","orgone","Oranur experiment","Geiger-Müller counter","vital energy","radioactivity"],"key_claims":["Harrer's account of Reich's Oranur experiments — over-excitation of vital energy (orgone) measured with the Geiger-Müller counter, probing the interaction between orgone and nuclear radiation"],"cross_references":["reich"],"status":"ok"},
    {"id":"prana-urja-abhivardhan-man-prana-energy-augmentation-hi","title":"मनुष्य की प्राण ऊर्जा और उसका अभिवर्धन (Man's Prana Energy and Its Augmentation) (hi→EN)","authors":[],"date":"2026-10-04","language":"hi","translated":True,"file":"translations/2026-10-04-prana-urja-abhivardhan-man-prana-energy-augmentation-hi.md","themes":["Consciousness & Subtle Energy","Water, Life & Biology"],"concepts":["prana","vital force","yogic physiology","energy augmentation"],"key_claims":["Hindi-language treatise on prana (vital energy) as the power source of the human organism and traditional methods of its augmentation"],"cross_references":[],"status":"ok"},
    {"id":"plasma-cross-collision-model-fusion-li-zh","title":"A Plasma Cross-Collision Model for Controlled Thermonuclear Fusion (Li) (zh→EN)","authors":[],"date":"2026-10-04","language":"zh","translated":True,"file":"translations/2026-10-04-plasma-cross-collision-model-fusion-li-zh.md","themes":["Plasma, Torsion & Cosmology","Alternative Energy Technologies"],"concepts":["plasma","controlled fusion","cross-collision model","thermonuclear"],"key_claims":["Chinese-language proposal of a plasma cross-collision configuration for controlled thermonuclear fusion — an alternative confinement geometry to tokamak magnetic confinement"],"cross_references":[],"status":"ok"},
    {"id":"phaenomen-rutengaenger-betz-de","title":"Hans-Dieter Betz — Phänomen Rutengänger (Anomalistik-Handbuch, Kap. 28) (de→EN)","authors":["hans-dieter-betz"],"date":"2026-10-04","language":"de","translated":True,"file":"translations/2026-10-04-phaenomen-rutengaenger-betz-de.md","themes":["Radionics, Radiesthesia & Shape Power","Skeptical Studies"],"concepts":["dowsing","radiesthesia","Rutengänger","anomalistics","skepticism"],"key_claims":["Betz's handbook chapter on the dowsing phenomenon — a critical-anomalistic survey of the historical and experimental record of the dowser","Note: author of the well-known Munich dowsing experiments; distinct from atmospheric physicist Walter Betz"],"cross_references":["valdmanis-dolacis-kalnin-dowsing-century-old-riddle-ru"],"status":"ok"},
    {"id":"valdmanis-dolacis-kalnin-dowsing-century-old-riddle-ru","title":"Валдманис, Долацис, Калнинь — Лозоходство: вековая загадка (Рига: Зинатне, 1979) (ru→EN)","authors":["valdmanis","dolacis","kalnin"],"date":"2026-10-04","language":"ru","translated":True,"file":"translations/2026-10-04-lozohodstvo-vekovaia-zagadka-valdmanis-ru.md","themes":["Radionics, Radiesthesia & Shape Power","History of Science"],"concepts":["dowsing","biophysical effects","Soviet-era research","radiesthesia"],"key_claims":["Soviet-era Latvian scientific monograph on dowsing (лозоходство) as a century-old riddle — instrumental and biophysical investigations of the dowsing effect"],"cross_references":["phaenomen-rutengaenger-betz-de","ermakov-beginners-dowsing-book-ru"],"status":"ok"},
    {"id":"jivani-shakti-vidyut-chumbkiyata-electromagnetism-vital-force-hi","title":"जीवनी शक्ति की विद्युत चुंबकीयता (The Electromagnetism of Vital Force) (hi→EN)","authors":[],"date":"2026-10-04","language":"hi","translated":True,"file":"translations/2026-10-04-jivani-shakti-vidyut-chumbkiyata-electromagnetism-vital-force-hi.md","themes":["Consciousness & Subtle Energy","Aether, Light & Electricity"],"concepts":["prana","vital force","electromagnetism","biophysics"],"key_claims":["Hindi-language essay arguing that vital force (jivani shakti) has electromagnetic characteristics — bridging traditional Indian vitalism with Western electrical science"],"cross_references":["prana-urja-abhivardhan-man-prana-energy-augmentation-hi"],"status":"ok"},
    {"id":"control-solutions-melts-torsion-fields-sedelnikov-gurdin-ru","title":"Sedelnikov & Gurdin — Controlling the Properties of Solutions and Melts Using Torsion Fields (ru→EN)","authors":["sedelnikov","gurdin"],"date":"2026-10-04","language":"ru","translated":True,"file":"translations/2026-10-04-control-solutions-melts-torsion-fields-sedelnikov-gurdin-ru.md","themes":["Plasma, Torsion & Cosmology","Water Structure & Memory"],"concepts":["torsion fields","material science","melts","solutions","technological application"],"key_claims":["Omsk researchers (FGUP OMO im. Baranov; OmSTU) report experimental control of physical properties of solutions and melts using torsion-field emitters — an applied-materials claim within the Russian torsion tradition"],"cross_references":[],"status":"ok"},
    {"id":"condensed-matter-nuclear-science-zhang-zh","title":"Zhang Wushou — Experimental Research in Condensed-Matter Nuclear Science (Science/Shanghai 2010) (zh→EN)","authors":["zhang-wushou"],"date":"2026-10-04","language":"zh","translated":True,"file":"translations/2026-10-04-condensed-matter-nuclear-science-zhang-zh.md","themes":["Alternative Energy Technologies","History of Science"],"concepts":["cold fusion","condensed-matter nuclear science","low-energy nuclear reactions","LENR"],"key_claims":["Chinese-language review of experimental condensed-matter nuclear science (cold fusion/LENR) — surveying the field's experimental record and chemical independence of nuclear processes (Mössbauer exception)"],"cross_references":["fusione-fredda-storia-ricerca-italia-enea-it"],"status":"ok"},
    {"id":"ancient-greek-theaters-geoenergy-concentrators-cgri-el","title":"Τα αρχαιοελληνικά θέατρα από ενεργειακή εστίαση (Ancient Greek Theaters as Geo-Energy Concentrators, CGRI) (el→EN)","authors":[],"date":"2026-10-04","language":"el","translated":True,"file":"translations/2026-10-04-ancient-greek-theaters-geoenergy-concentrators-cgri-el.md","themes":["Sacred Geometry & Form","Geobiology"],"concepts":["geo-energy","form waves","Greek theater","energy concentration","sacred architecture"],"key_claims":["Greek-language study (Center for Geo-Energy Research & Information tradition) reading ancient Greek theaters as geo-energetic concentrators — form/place resonance in the Greek radiesthesia and geobiology lane"],"cross_references":[],"status":"ok"},
    {"id":"wichelen-dowsing-olsthoorn-nl","title":"Wichelen (Dowsing) — Theo Olsthoorn, Stromingen 14 (2008) nr. 3 (nl→EN)","authors":["theo-olsthoorn"],"date":"2026-10-03","language":"nl","translated":True,"file":"translations/2026-10-03-wichelen-dowsing-olsthoorn-nl.md","themes":["Radionics, Radiesthesia & Shape Power","Skeptical Studies"],"concepts":["dowsing","wichelroede","groundwater","Dutch hydrology"],"key_claims":["Dutch-language article on dowsing (wichelen) in hydrological practice — context from the NHV symposium 'Grondwater, Bron van Leven', participants experiencing dowsing for groundwater"],"cross_references":["phaenomen-rutengaenger-betz-de"],},
    {"id":"turkish-radiesthesia-selected-pages-tr","title":"Turkish Radiesthesia — Selected Pages (radyestezibilimi.tr.gq) (tr→EN)","authors":[],"date":"2026-10-03","language":"tr","translated":True,"file":"translations/2026-10-03-turkish-radiesthesia-selected-pages-tr.md","themes":["Radionics, Radiesthesia & Shape Power"],"concepts":["radiesthesia","radyestezi","pendulum","Turkish school"],"key_claims":["Selected pages from the Turkish radiesthesia site radyestezibilimi — first Turkish-language entries in the collection ('What is Radiesthesia' and related pages)"],"cross_references":[],"status":"ok"},
    {"id":"radiestezja-od-podstaw-sitkowski-pl","title":"Radiestezja od podstaw (Tomasz Sitkowski) (pl→EN)","authors":["sitkowski"],"date":"2026-10-03","language":"pl","translated":True,"file":"translations/2026-10-03-radiestezja-od-podstaw-sitkowski-pl.md","themes":["Radionics, Radiesthesia & Shape Power"],"concepts":["radiesthesia","pendulum","two systems of assessment","Polish school"],"key_claims":["Sitkowski's 'Radiesthesia from the Basics' — archived source is a 17-page publisher sampler (front matter, TOC, 'From the Author', definition/history of radiesthesia, 'Two Systems of Assessment')"],"cross_references":["radiestezja-mentalna-sitkowski-pl","radiestezja-dla-dociekliwych-sitkowski-pl"],"status":"ok"},
    {"id":"radiestezja-mentalna-sitkowski-pl","title":"Radiestezja mentalna (Tomasz Sitkowski) (pl→EN)","authors":["sitkowski"],"date":"2026-10-03","language":"pl","translated":True,"file":"translations/2026-10-03-radiestezja-mentalna-sitkowski-pl.md","themes":["Radionics, Radiesthesia & Shape Power","Consciousness & Subtle Energy"],"concepts":["mental radiesthesia","pendulum","operator training","Polish school"],"key_claims":["Sitkowski's 'Mental Radiesthesia' — contemporary interpretation of the method with practical advice for increasing radiesthetic effectiveness"],"cross_references":["radiestezja-od-podstaw-sitkowski-pl","radiestezja-dla-dociekliwych-sitkowski-pl"],"status":"ok"},
    {"id":"radiestesia-integral-gerula-es","title":"Radiestesia Integral (Padre Luis Gerula, Kier 2001) (es→EN)","authors":["luis-gerula"],"date":"2026-10-03","language":"es","translated":True,"file":"translations/2026-10-03-radiestesia-integral-gerula-es.md","themes":["Radionics, Radiesthesia & Shape Power"],"concepts":["integral radiesthesia","pendulum","Catholic tradition","Spanish-language school"],"key_claims":["'Radiestesia Integral' by Padre Luis Gerula (Kier, 2001) — Spanish-language integral radiesthesia manual from the Catholic dowsing tradition"],"cross_references":[],"status":"ok"},
    {"id":"ondes-de-forme-radionique-magnetotherapie-fr","title":"Ondes de forme, radionique, magnétothérapie (French radionic form-waves compilation) (fr→EN)","authors":[],"date":"2026-10-03","language":"fr","translated":True,"file":"translations/2026-10-03-ondes-de-forme-radionique-magnetotherapie-fr.md","themes":["Radionics, Radiesthesia & Shape Power","Sacred Geometry & Form"],"concepts":["ondes de forme","radionics","magnetotherapy","Cellsensor","electromagnetic pollution"],"key_claims":["French-language compilation on radionic form waves and magnetotherapy — practical instrument use (Cellsensor) against electromagnetic pollution from modern appliances and high-voltage lines"],"cross_references":[],},
    {"id":"ermakov-beginners-dowsing-book-ru","title":"Книга начинающего лозоходца (Станислав Ермаков, 2007) (ru→EN)","authors":["stanislav-ermakov"],"date":"2026-10-03","language":"ru","translated":True,"file":"translations/2026-10-03-kniga-nachinayuschego-lozohodtsa-ermakov-ru.md","themes":["Radionics, Radiesthesia & Shape Power","Geobiology"],"concepts":["dowsing","лозоходство","beginner's manual","sacred geography"],"key_claims":["Ermakov's practical self-study manual of dowsing (лозоходство) — entry into the Russian dowsing/geobiology tradition; author is the cultural scholar Stanislav E. Ermakov, distinct from water-structure researcher Ermakova"],"cross_references":["valdmanis-dolacis-kalnin-dowsing-century-old-riddle-ru"],},
    {"id":"fusione-fredda-storia-ricerca-italia-enea-it","title":"Fusione Fredda: Storia della ricerca in Italia (ENEA, eds. Martellucci, Rosati, Scaramuzzi, Violante, 2008) (it→EN)","authors":["sergio-martellucci","angela-rosati","francesco-scaramuzzi","vittorio-violante"],"date":"2026-10-03","language":"it","translated":True,"file":"translations/2026-10-03-fusione-fredda-storia-ricerca-italia-enea-it.md","themes":["Alternative Energy Technologies","History of Science"],"concepts":["cold fusion","ENEA","Italian research history","Francesco Scaramuzzi","low-energy nuclear reactions"],"key_claims":["Official ENEA-edited history of cold fusion research in Italy — the definitive institutional account of the Italian program (Scaramuzzi's deuterium gas-loading experiments, ENEA's role)"],"cross_references":["condensed-matter-nuclear-science-zhang-zh"],},
    {"id":"elektromagnitnye-solitony-vakuuma-ch2-smelov-ru","title":"М.В. Смелов — Электромагнитные солитоны вакуума. Часть 2: Топологические характеристики электромагнитных солитонов (ru→EN)","authors":["smelov"],"date":"2026-10-03","language":"ru","translated":True,"file":"translations/2026-10-03-elektromagnitnye-solitony-vakuuma-ch2-smelov-ru.md","themes":["Plasma, Torsion & Cosmology","Unified Theory"],"concepts":["electromagnetic solitons","vacuum structure","topology","Academy of Trinitarianism"],"key_claims":["Smelov's Part 2 on topological characteristics of electromagnetic solitons of the vacuum — Academy of Trinitarianism unified-field lane"],"cross_references":[],},
    {"id":"cosmic-influence-random-processes-radioactive-decay-corona-discharge-tatur-ru","title":"Tatur, Lukyanitsa & Shishkin — Correlations in cosmic influence on random processes: radioactive decay and corona discharge (Вестник МАСИ 2025) (ru→EN)","authors":["tatur","lukyanitsa","shishkin"],"date":"2026-10-03","language":"ru","translated":True,"file":"translations/2026-10-03-cosmic-influence-random-processes-radioactive-decay-corona-discharge-tatur-ru.md","themes":["Consciousness Research","Plasma, Torsion & Cosmology"],"concepts":["random processes","radioactive decay","corona discharge","cosmic influence","MACI"],"key_claims":["Вестник МАСИ 2025 paper reporting correlations of cosmic influence on random processes — simultaneous deviations in radioactive decay and corona discharge statistics"],"cross_references":[],},
    {"id":"abc-wahadla-matela-pl","title":"ABC wahadła (Leszek Matela, wyd. 11) (pl→EN)","authors":["leszek-matela"],"date":"2026-10-03","language":"pl","translated":True,"file":"translations/2026-10-03-abc-wahadla-matela-pl.md","themes":["Radionics, Radiesthesia & Shape Power"],"concepts":["pendulum","wahadło","Polish school","dowsing practice"],"key_claims":["Matela's 'ABC of the Pendulum' (11th edition) — archived source is a 35-page publisher excerpt (front matter, full TOC, Part One sections 1.1–1.15 through the Swiss-grid section)"],"cross_references":["radiestezja-od-podstaw-sitkowski-pl"],},
]

PERSONS = [
    {"id":"hans-dieter-betz","name":"Hans-Dieter Betz","nationality":"German","role":"physicist, dowsing researcher","key_contribution":"Author of the Anomalistik-Handbuch chapter 'Phänomen Rutengänger'; known for the Munich dowsing experiments — the most rigorous institutional test of dowsing claims. Distinct from atmospheric physicist Walter Betz.","works_in_collection":["translations/2026-10-04-phaenomen-rutengaenger-betz-de.md"],"cited_by":[],"notes":""},
    {"id":"valdmanis","name":"Ya. Ya. Valdmanis","nationality":"Latvian/Soviet","role":"dowsing researcher","key_contribution":"Co-author of 'Лозоходство: вековая загадка' (Dowsing — a Century-Old Riddle, Riga: Zinatne, 1979) — Soviet-era instrumental study of dowsing","works_in_collection":["translations/2026-10-04-lozohodstvo-vekovaia-zagadka-valdmanis-ru.md"],"cited_by":[],"notes":""},
    {"id":"dolacis","name":"Ya. A. Dolatsis","nationality":"Latvian/Soviet","role":"dowsing researcher","key_contribution":"Co-author of 'Лозоходство: вековая загадка' (Riga: Zinatne, 1979)","works_in_collection":["translations/2026-10-04-lozohodstvo-vekovaia-zagadka-valdmanis-ru.md"],"cited_by":[],"notes":""},
    {"id":"kalnin","name":"T. K. Kalnin","nationality":"Latvian/Soviet","role":"dowsing researcher","key_contribution":"Co-author of 'Лозоходство: вековая загадка' (Riga: Zinatne, 1979)","works_in_collection":["translations/2026-10-04-lozohodstvo-vekovaia-zagadka-valdmanis-ru.md"],"cited_by":[],"notes":""},
    {"id":"sedelnikov","name":"Vladimir Vasilyevich Sedelnikov","nationality":"Russian","role":"materials researcher (FGUP OMO im. P.I. Baranov, Omsk)","key_contribution":"Co-author of experimental reports on controlling properties of solutions and melts using torsion fields","works_in_collection":["translations/2026-10-04-control-solutions-melts-torsion-fields-sedelnikov-gurdin-ru.md"],"cited_by":[],"notes":""},
    {"id":"gurdin","name":"Viktor Ivanovich Gurdin","nationality":"Russian","role":"researcher, Omsk State Technical University","key_contribution":"Co-author of experimental reports on controlling properties of solutions and melts using torsion fields","works_in_collection":["translations/2026-10-04-control-solutions-melts-torsion-fields-sedelnikov-gurdin-ru.md"],"cited_by":[],"notes":""},
    {"id":"zhang-wushou","name":"Zhang Wushou","nationality":"Chinese","role":"condensed-matter nuclear science researcher","key_contribution":"Author of the Science (Shanghai) 2010 review of experimental condensed-matter nuclear science (cold fusion/LENR)","works_in_collection":["translations/2026-10-04-condensed-matter-nuclear-science-zhang-zh.md"],"cited_by":[],"notes":""},
    {"id":"theo-olsthoorn","name":"Theo Olsthoorn","nationality":"Dutch","role":"hydrologist, dowsing writer","key_contribution":"Author of 'Wichelen' (Stromingen 14, 2008) on dowsing in Dutch groundwater practice","works_in_collection":["translations/2026-10-03-wichelen-dowsing-olsthoorn-nl.md"],"cited_by":[],"notes":""},
    {"id":"luis-gerula","name":"Padre Luis Gerula","nationality":"Argentine/Spanish-language","role":"Catholic priest, radiesthesia author","key_contribution":"Author of 'Radiestesia Integral' (Kier, 2001) — integral radiesthesia in the Catholic dowsing tradition","works_in_collection":["translations/2026-10-03-radiestesia-integral-gerula-es.md"],"cited_by":[],"notes":""},
    {"id":"stanislav-ermakov","name":"Stanislav Eduardovich Ermakov","nationality":"Russian","role":"cultural scholar (kandidat of cultural studies), dowsing author","key_contribution":"Author of 'Книга начинающего лозоходца' (2007) and works on sacred geography; specialist in intangible cultural heritage. Distinct from water-structure researcher Ermakova.","works_in_collection":["translations/2026-10-03-kniga-nachinayuschego-lozohodtsa-ermakov-ru.md"],"cited_by":[],"notes":""},
    {"id":"sergio-martellucci","name":"Sergio Martellucci","nationality":"Italian","role":"physicist, editor (ENEA)","key_contribution":"Co-editor of 'Fusione Fredda: Storia della ricerca in Italia' (ENEA, 2008)","works_in_collection":["translations/2026-10-03-fusione-fredda-storia-ricerca-italia-enea-it.md"],"cited_by":[],"notes":""},
    {"id":"angela-rosati","name":"Angela Rosati","nationality":"Italian","role":"researcher, editor (ENEA)","key_contribution":"Co-editor of 'Fusione Fredda: Storia della ricerca in Italia' (ENEA, 2008)","works_in_collection":["translations/2026-10-03-fusione-fredda-storia-ricerca-italia-enea-it.md"],"cited_by":[],"notes":""},
    {"id":"francesco-scaramuzzi","name":"Francesco Scaramuzzi","nationality":"Italian","role":"physicist, cold fusion pioneer (ENEA/Frascati)","key_contribution":"Co-editor of the ENEA cold-fusion history; led the Frascati deuterium gas-loading excess-heat experiments — central figure of Italian cold fusion research","works_in_collection":["translations/2026-10-03-fusione-fredda-storia-ricerca-italia-enea-it.md"],"cited_by":[],"notes":""},
    {"id":"vittorio-violante","nationality_placeholder":None,"name":"Vittorio Violante","role":"researcher, editor (ENEA)","key_contribution":"Co-editor of 'Fusione Fredda: Storia della ricerca in Italia' (ENEA, 2008); ENEA researcher on palladium deuterium loading","works_in_collection":["translations/2026-10-03-fusione-fredda-storia-ricerca-italia-enea-it.md"],"cited_by":[],"notes":""},
    {"id":"smelov","name":"M.V. Smelov","nationality":"Russian","role":"theoretical physicist (Academy of Trinitarianism)","key_contribution":"Author of the 'Electromagnetic Solitons of the Vacuum' series — topological characteristics of vacuum solitons in the Trinitarian unified-field tradition","works_in_collection":["translations/2026-10-03-elektromagnitnye-solitony-vakuuma-ch2-smelov-ru.md"],"cited_by":[],"notes":""},
    {"id":"tatur","name":"V.Yu. Tatur","nationality":"Russian","role":"researcher (MACI)","key_contribution":"Lead author of the Вестник МАСИ 2025 study on correlations in cosmic influence on random processes (radioactive decay, corona discharge)","works_in_collection":["translations/2026-10-03-cosmic-influence-random-processes-radioactive-decay-corona-discharge-tatur-ru.md"],"cited_by":[],"notes":""},
    {"id":"lukyanitsa","name":"A.A. Lukyanitsa","nationality":"Russian","role":"researcher (MACI)","key_contribution":"Co-author of the Вестник МАСИ 2025 cosmic-influence/random-processes correlation study","works_in_collection":["translations/2026-10-03-cosmic-influence-random-processes-radioactive-decay-corona-discharge-tatur-ru.md"],"cited_by":[],"notes":""},
    {"id":"shishkin","name":"A.L. Shishkin","nationality":"Russian","role":"researcher (MACI)","key_contribution":"Co-author of the Вестник МАСИ 2025 cosmic-influence/random-processes correlation study","works_in_collection":["translations/2026-10-03-cosmic-influence-random-processes-radioactive-decay-corona-discharge-tatur-ru.md"],"cited_by":[],"notes":""},
    {"id":"leszek-matela","name":"Leszek Matela","nationality":"Polish","role":"radiesthesia author","key_contribution":"Author of 'ABC wahadła' (11th ed.) — pendulum radiesthesia in the Polish school; prolific Polish author on dowsing and sacred geometry","works_in_collection":["translations/2026-10-03-abc-wahadla-matela-pl.md"],"cited_by":[],"notes":""},
]

for path, key, additions in [("database/research-index.json","works",WORKS),("database/person-index.json","persons",PERSONS)]:
    data = json.load(open(path))
    lst = data[key] if key in data else data
    existing_ids = {x["id"] for x in lst}
    existing_files = {x.get("file","").split("/")[-1] for x in lst}
    added = 0
    for a in additions:
        a = {k:v for k,v in a.items() if not k.endswith("_placeholder")}
        if a["id"] in existing_ids: continue
        if key == "works" and a.get("file","").split("/")[-1] in existing_files: continue
        lst.append(a); added += 1
    json.dump(data, open(path,"w"), ensure_ascii=False, indent=2)
    open(path,"a").write("\n")
    print(path, "added", added, "->", len(lst))
